# Third-party repositories used by direct workstation dependencies.
tap "bufbuild/buf"
tap "gofireflyio/aiac"
tap "hashicorp/tap"
tap "telepresenceio/telepresence"
tap "terraform-linters/tap"
tap "tilt-dev/tap"
tap "turbot/tap"
tap "yoheimuta/protolint"

# Shell, editor, and dotfile tooling.
brew "age"
brew "bash"
brew "chezmoi"
brew "coreutils"
brew "direnv"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "jq"
brew "mise"
brew "neovim"
brew "ripgrep"
brew "sesh"
brew "shellcheck"
brew "shfmt"
brew "sops"
brew "starship"
brew "tmux"
brew "tree"
brew "yq"
brew "zoxide"

# Cloud provider tooling.
brew "aws-vault"
brew "awscli"
brew "azure-cli"
brew "eksctl"
brew "turbot/tap/steampipe"

# Kubernetes, GitOps, and container tooling.
brew "argocd"
brew "cosign"
brew "dive"
brew "fluxcd"
brew "grype"
brew "helm"
brew "helm-docs"
brew "helmfile"
brew "k3d"
brew "k9s"
brew "kind"
brew "kube-linter"
brew "kube-score"
brew "kubeconform"
brew "kubebuilder"
brew "kubectx"
brew "kubent"
brew "kubernetes-cli"
brew "kubeseal"
brew "kustomize"
brew "operator-sdk"
brew "oras"
brew "qemu"
brew "skaffold"
brew "stern"
brew "syft"
brew "telepresenceio/telepresence/telepresence-oss"
brew "tilt-dev/tap/ctlptl"
brew "tilt-dev/tap/tilt"
brew "trivy"

# Terraform and infrastructure-as-code tooling.
brew "hcl2json"
brew "opentofu"
brew "terraform-docs"
brew "terragrunt"
brew "tfmigrate"
brew "hashicorp/tap/terraform"
brew "terraform-linters/tap/tflint"

# Application, API, and documentation tooling.
brew "bufbuild/buf/buf"
brew "cdk8s"
brew "cue"
brew "d2"
brew "gofireflyio/aiac/aiac"
brew "goreleaser"
brew "graphviz"
brew "grpcurl"
brew "hey"
brew "httpie"
brew "hugo"
brew "kcat"
brew "llvm"
brew "mdbook"
brew "protobuf"
brew "protoc-gen-go"
brew "protoc-gen-go-grpc"
brew "yoheimuta/protolint/protolint"
brew "yj"

# Desktop applications and fonts.
cask "1password-cli"
cask "font-3270-nerd-font"
cask "gcloud-cli"
cask "ghostty"
cask "ngrok"
cask "obsidian"
cask "orbstack"
